package com.example.deckphonephone.deck.application

data class DeckUseCases(
    val createCategory: CreateCategoryUseCase,
    val observeCategories: ObserveCategoriesUseCase,
    val updateCategory: UpdateCategoryUseCase,
    val deleteCategory: DeleteCategoryUseCase,
    val createTextActionCard: CreateTextActionCardUseCase,
    val createWebActionCard: CreateWebActionCardUseCase,
    val createBluetoothDeviceActionCard: CreateBluetoothDeviceActionCardUseCase,
    val listPairedBluetoothDevices: ListPairedBluetoothDevicesUseCase,
    val observeConnectedBluetoothDevices: ObserveConnectedBluetoothDevicesUseCase,
    val observeActionCards: ObserveActionCardsUseCase,
    val updateTextActionCard: UpdateTextActionCardUseCase,
    val updateWebActionCard: UpdateWebActionCardUseCase,
    val updateBluetoothDeviceActionCard: UpdateBluetoothDeviceActionCardUseCase,
    val deleteActionCard: DeleteActionCardUseCase,
    val setActionCardEnabled: SetActionCardEnabledUseCase,
    val executeActionCard: ExecuteActionCardUseCase,
    val observeDarkTheme: ObserveDarkThemeUseCase,
    val setDarkTheme: SetDarkThemeUseCase,
    val observeColorTheme: ObserveColorThemeUseCase,
    val setColorTheme: SetColorThemeUseCase,
    val observeOverlayHandPreference: ObserveOverlayHandPreferenceUseCase,
    val setOverlayHandPreference: SetOverlayHandPreferenceUseCase,
)
